apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nvidia-device-plugin

helmCharts:
  - name: nvidia-device-plugin
    repo: https://nvidia.github.io/k8s-device-plugin
    releaseName: nvdp
    namespace: nvidia-device-plugin
    version: 0.18.0
    # valuesFile: values.yaml
